### PR TITLE
AOSP keyboard: default dark theme variant

### PR DESCRIPTION
**Pull request by dimqua**

### CODE REVIEW

**Comment by SpiritCroc** [comment]
Thanks for contributing! Have you overlayed/looked into the space bar color? #424242 (or #303030) would match the rest of the theme probably more than #383838 (I think what it is now).
Personally, I'd prefer #303030 as bg color but #212121 is fine as well (unfortunately, we cannot reference background_material_dark here).
Some other colors are also not quite fitting the rest color selection of the theme (e.g. #1e1e1e), common background colors would be #000000, #212121, #303030, #424242, and #616161.

**Comment by dimqua** [comment]
>Have you overlayed/looked into the space bar color?

Unfortunable, I didn't find a way to change it.

**Comment by SpiritCroc** [comment]
Hm ok, will try to look into it if I find time

**Comment by SpiritCroc** [comment]
Picked & pushed, should be good enough as is for now (I'm too lazy to work on it since I won't use it either way :) ).
Thanks again for contributing!

**Pull request closed without merging**
